name: "detec_onnx"
default_model_filename: "detec_onnx.onnx"
platform: "onnxruntime_onnx"
max_batch_size : 1
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1, 2 ]
  },
  {
    name: "281"
    data_type: TYPE_FP32
    dims: [ 32, -1, -1 ]
  }
]